### PR TITLE
Time recorder for wr log changes

### PR DESCRIPTION
**Pull request by mvillena3**
The time is recorded in the wr_log when an email is sent to a receiver, when the receiver opens the email, and when the receiver clicks Worth Reading.

### CODE REVIEW

**Comment by jhm15217** [comment]
Excellent!

I notice that the model, wr_logs.rb, doesn't mention the new fields. I
don't understand how this works. Can we still access them to create reports?

On Thu, Aug 2, 2012 at 5:21 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> The time is recorded in the wr_log when an email is sent to a receiver,
> when the receiver opens the email, and when the receiver clicks Worth
> Reading.
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/jhm15217/worthreadingtime-recorder-for-wr-log-changes
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/jhm15217/worthreading/pull/41
> 
> -- Commit Summary --
> - Restrictor from sending another worthreading email if it is clicked more
>   than once
> - Haml conversion
> - Changed views for response to wr_log
> - Added columns for storing times for wr_logs
> - Test for time recorded when email is sent
> - Code and test for recording time when email is opened
> - Code and test for recording the time when a user finds a message worth
>   reading
> 
> -- File Changes --
> 
> M app/controllers/users_controller.rb (2)
> M app/controllers/wr_logs_controller.rb (6)
> M app/models/email.rb (9)
> M app/models/user.rb (11)
> D app/views/wr_logs/show.html.erb (35)
> A app/views/wr_logs/show.html.haml (36)
> A db/migrate/20120802185927_add_timers_to_wr_logs.rb (7)
> M db/schema.rb (5)
> M spec/controllers/wr_logs_controller_spec.rb (9)
> M spec/models/user_spec.rb (5)
> M spec/views/wr_logs/show.html.erb_spec.rb (27)
> 
> -- Patch Links --
> 
>   https://github.com/jhm15217/worthreading/pull/41.patch
>   https://github.com/jhm15217/worthreading/pull/41.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/pull/41

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
I forgot to annotate them. I'll do it right now and push it up.

On Thu, Aug 2, 2012 at 5:07 PM, James Morris <
reply@reply.github.com

**Comment by jhm15217** [comment]
I see that schema.rb reflects the lastest version. Wr_logs.rb, on the other
hand, even lists the obsoleted :responded as an attribute.  What does
wr_logs.rb get used for, anyway?

On Thu, Aug 2, 2012 at 6:07 PM, james.morris@cmu.edu wrote:

> Excellent!
> 
> I notice that the model, wr_logs.rb, doesn't mention the new fields. I
> don't understand how this works. Can we still access them to create reports?
> 
> On Thu, Aug 2, 2012 at 5:21 PM, mvillena3 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > The time is recorded in the wr_log when an email is sent to a receiver,
> > when the receiver opens the email, and when the receiver clicks Worth
> > Reading.
> > 
> > You can merge this Pull Request by running:
> > 
> >   git pull https://github.com/jhm15217/worthreadingtime-recorder-for-wr-log-changes
> > 
> > Or you can view, comment on it, or merge it online at:
> > 
> >   https://github.com/jhm15217/worthreading/pull/41
> > 
> > -- Commit Summary --
> > - Restrictor from sending another worthreading email if it is clicked
> >   more than once
> > - Haml conversion
> > - Changed views for response to wr_log
> > - Added columns for storing times for wr_logs
> > - Test for time recorded when email is sent
> > - Code and test for recording time when email is opened
> > - Code and test for recording the time when a user finds a message worth
> >   reading
> > 
> > -- File Changes --
> > 
> > M app/controllers/users_controller.rb (2)
> > M app/controllers/wr_logs_controller.rb (6)
> > M app/models/email.rb (9)
> > M app/models/user.rb (11)
> > D app/views/wr_logs/show.html.erb (35)
> > A app/views/wr_logs/show.html.haml (36)
> > A db/migrate/20120802185927_add_timers_to_wr_logs.rb (7)
> > M db/schema.rb (5)
> > M spec/controllers/wr_logs_controller_spec.rb (9)
> > M spec/models/user_spec.rb (5)
> > M spec/views/wr_logs/show.html.erb_spec.rb (27)
> > 
> > -- Patch Links --
> > 
> >   https://github.com/jhm15217/worthreading/pull/41.patch
> >   https://github.com/jhm15217/worthreading/pull/41.diff
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jhm15217/worthreading/pull/41
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
I didn't realize we wanted to remove the :responded attribute. I can go ahead and remove the column from the database.

The wr_log.rb has the class WrLog which acts as the object that connects to the wr_logs table in the database. Thus, WrLog.new, WrLog.create, etc. Also, it is where we can add validations, attr_accessible, model associations.

**Comment by jhm15217** [comment]
... and most of the methods we use are already in the superclass
ActiveRecord, right? Remind me what attr_accessible does? Limit the user's
ability to change them directly, or what?

On Thu, Aug 2, 2012 at 6:18 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> I didn't realize we wanted to remove the :responded attribute. I can go
> ahead and remove the column from the database.
> 
> The wr_log.rb has the class WrLog which acts as the object that connects
> to the wr_logs table in the database. Thus, WrLog.new, WrLog.create, etc.
> Also, it is where we can add validations, attr_accessible, model
> associations.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/pull/41#issuecomment-7468501

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
Yes, create, new, find, etc. all come formt he superclass.

attr_accessible prevents certain attributes from being mass-assigned. Thus,
certain attributes cannot be assigned simply through WrLog.create or
WrLog.new.

For example for a User object:
User.create(name: "John", admin: true)

We wouldn't want anybody to just assign admin to true. So our
attr_accessible would like
attr_accessible :name
but admin wouldn't be there to prevent a hacker from mass-assigning
themselves as admin.

On Thu, Aug 2, 2012 at 5:22 PM, James Morris <
reply@reply.github.com

**Pull request merged**
