### PR TITLE
Email system

### PR DESCRIPTION
**Pull request by mvillena3**
The working code for receiving emails.

### CODE REVIEW

**Comment by jhm15217** [comment]
OK. I think I merged it.

I'm still confused about conflicts, after lots of googling!

I've hassled with the mergetool, but how would I say "forget my unpushed
changes, just accept mike's", for example?

On Thu, Jul 12, 2012 at 5:35 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/jhm15217/worthreading email-system
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/jhm15217/worthreading/pull/4
> 
> -- Commit Summary --
> - Working user email association
> - Working email tests and passing functions
> - Working tests, and working controllers
> - Emails tests and tweaks
> - Added gem Thin
> 
> -- File Changes --
> 
> M Gemfile (1)
> M Gemfile.lock (7)
> M app/controllers/emails_controller.rb (31)
> M app/models/email.rb (15)
> M app/models/user.rb (1)
> A db/migrate/20120712183426_add_user_id_to_emails.rb (5)
> M db/schema.rb (3)
> M spec/controllers/emails_controller_spec.rb (178)
> M spec/factories.rb (12)
> M spec/models/email_spec.rb (62)
> M spec/models/user_spec.rb (62)
> M spec/requests/user_pages_spec.rb (2)
> 
> -- Patch Links --
> 
>   https://github.com/jhm15217/worthreading/pull/4.patch
>   https://github.com/jhm15217/worthreading/pull/4.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/pull/4

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Also, we should automatically register unknown users, marking them as
"auto-registered", and forward their emails just as if they were
voluntarily registered. If they ever voluntarily register we might need to
adjust their balance and do other things.

On Thu, Jul 12, 2012 at 6:25 PM, james.morris@cmu.edu wrote:

> OK. I think I merged it.
> 
> I'm still confused about conflicts, after lots of googling!
> 
> I've hassled with the mergetool, but how would I say "forget my unpushed
> changes, just accept mike's", for example?
> 
> On Thu, Jul 12, 2012 at 5:35 PM, mvillena3 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > You can merge this Pull Request by running:
> > 
> >   git pull https://github.com/jhm15217/worthreading email-system
> > 
> > Or you can view, comment on it, or merge it online at:
> > 
> >   https://github.com/jhm15217/worthreading/pull/4
> > 
> > -- Commit Summary --
> > - Working user email association
> > - Working email tests and passing functions
> > - Working tests, and working controllers
> > - Emails tests and tweaks
> > - Added gem Thin
> > 
> > -- File Changes --
> > 
> > M Gemfile (1)
> > M Gemfile.lock (7)
> > M app/controllers/emails_controller.rb (31)
> > M app/models/email.rb (15)
> > M app/models/user.rb (1)
> > A db/migrate/20120712183426_add_user_id_to_emails.rb (5)
> > M db/schema.rb (3)
> > M spec/controllers/emails_controller_spec.rb (178)
> > M spec/factories.rb (12)
> > M spec/models/email_spec.rb (62)
> > M spec/models/user_spec.rb (62)
> > M spec/requests/user_pages_spec.rb (2)
> > 
> > -- Patch Links --
> > 
> >   https://github.com/jhm15217/worthreading/pull/4.patch
> >   https://github.com/jhm15217/worthreading/pull/4.diff
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jhm15217/worthreading/pull/4
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Finally, we should probably beef up our registration procedure someday by
sending them an email they must confirm, which will prevent hackers from
pre-empting legitimate users.

On Thu, Jul 12, 2012 at 6:29 PM, james.morris@cmu.edu wrote:

> Also, we should automatically register unknown users, marking them as
> "auto-registered", and forward their emails just as if they were
> voluntarily registered. If they ever voluntarily register we might need to
> adjust their balance and do other things.
> 
> On Thu, Jul 12, 2012 at 6:25 PM, james.morris@cmu.edu wrote:
> 
> > OK. I think I merged it.
> > 
> > I'm still confused about conflicts, after lots of googling!
> > 
> > I've hassled with the mergetool, but how would I say "forget my unpushed
> > changes, just accept mike's", for example?
> > 
> > On Thu, Jul 12, 2012 at 5:35 PM, mvillena3 <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > You can merge this Pull Request by running:
> > > 
> > >   git pull https://github.com/jhm15217/worthreading email-system
> > > 
> > > Or you can view, comment on it, or merge it online at:
> > > 
> > >   https://github.com/jhm15217/worthreading/pull/4
> > > 
> > > -- Commit Summary --
> > > - Working user email association
> > > - Working email tests and passing functions
> > > - Working tests, and working controllers
> > > - Emails tests and tweaks
> > > - Added gem Thin
> > > 
> > > -- File Changes --
> > > 
> > > M Gemfile (1)
> > > M Gemfile.lock (7)
> > > M app/controllers/emails_controller.rb (31)
> > > M app/models/email.rb (15)
> > > M app/models/user.rb (1)
> > > A db/migrate/20120712183426_add_user_id_to_emails.rb (5)
> > > M db/schema.rb (3)
> > > M spec/controllers/emails_controller_spec.rb (178)
> > > M spec/factories.rb (12)
> > > M spec/models/email_spec.rb (62)
> > > M spec/models/user_spec.rb (62)
> > > M spec/requests/user_pages_spec.rb (2)
> > > 
> > > -- Patch Links --
> > > 
> > >   https://github.com/jhm15217/worthreading/pull/4.patch
> > >   https://github.com/jhm15217/worthreading/pull/4.diff
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/jhm15217/worthreading/pull/4
> > 
> > ## 
> > 
> > James H. Morris
> > http://www.cs.cmu.edu/~jhm
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
About the github issue of merge conlficts. If you would like to say "forget my unpushed changes, just accept mike's," then you could run a sequence like:

```
git checkout .   
git clean -f       
git pull
```

So first, you git checkout to undo modifications to existing files. You then git clean to delete any new files you create that you want to delete. Then I would lastly use a git pull to pull in the remote master repository.

However, if the changes were committed, you might have to run a sequence like:
`git reflog`
Then search the log for the change before you commits. Then:
`git reset --hard XXXXX`
where XXXX is the change you would like to revert back to.
Then you can git pull.

A last resort, would be to pull off another git clone.

Usually, one would work on another branch apart from the master.  That way changes on that branch can be easily be deleted just by deleting that branch. Then you would push up that branch and use a pull request to request a merge towards the master branch.

If you wanted to test that branch on heroku you could push to heroku using:
`git push heroku yourbranch:master`

**Comment by mvillena3** [comment]
Also the features you mentioned above, I will place in the issue list to keep track of the features we need to develop.

**Comment by mvillena3** [comment]
Feel free to add features in the issue list that we need to work on developing.

**Pull request merged**
