### PR TITLE
Web beacon

### PR DESCRIPTION
**Pull request by mvillena3**
Got a working web beacon inserted to the email. The server response is a change in the action of the wr_log to "opened" and responded set to true. I created some tests also. I'll need to tweak it up more on Monday but I got the basic functionality working.

### CODE REVIEW

**Comment by jhm15217** [comment]
Good work!

BTW: The email confirm mechanism is interfering with my testing a little
since those 100 users from populate have email addresses that don't come to
us. Can we do something about that?

On Fri, Jul 27, 2012 at 6:13 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> Got a working web beacon inserted to the email. The server response is a
> change in the action of the wr_log to "opened" and responded set to true. I
> created some tests also. I'll need to tweak it up more on Monday but I got
> the basic functionality working.
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/jhm15217/worthreading web-beacon
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/jhm15217/worthreading/pull/33
> 
> -- Commit Summary --
> - Added web beacon to email
> - Connected beacon to server
> - Log is modified when email open
> - Tweaking code
> - Getting web beacon to respond to server
> - Fixed error
> - Trying to get db to respond
> - Some tests for the web beacon
> - Tweaking again
> 
> -- File Changes --
> 
> D app/assets/images/rails.png (0)
> M app/controllers/wr_logs_controller.rb (17)
> M app/mailers/user_mailer.rb (2)
> M app/views/user_mailer/send_message.html.haml (6)
> M app/views/wr_logs/index.html.erb (1)
> M config/routes.rb (10)
> A public/images/beacon.gif (0)
> A public/images/test.jpeg (0)
> M spec/controllers/wr_logs_controller_spec.rb (14)
> M spec/mailers/user_mailer_spec.rb (49)
> 
> -- Patch Links --
> 
>   https://github.com/jhm15217/worthreading/pull/33.patch
>   https://github.com/jhm15217/worthreading/pull/33.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/pull/33

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Maybe have populate mark them all confirmed. I'll try that.

On Fri, Jul 27, 2012 at 6:17 PM, james.morris@cmu.edu wrote:

> Good work!
> 
> BTW: The email confirm mechanism is interfering with my testing a little
> since those 100 users from populate have email addresses that don't come to
> us. Can we do something about that?
> 
> On Fri, Jul 27, 2012 at 6:13 PM, mvillena3 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Got a working web beacon inserted to the email. The server response is a
> > change in the action of the wr_log to "opened" and responded set to true. I
> > created some tests also. I'll need to tweak it up more on Monday but I got
> > the basic functionality working.
> > 
> > You can merge this Pull Request by running:
> > 
> >   git pull https://github.com/jhm15217/worthreading web-beacon
> > 
> > Or you can view, comment on it, or merge it online at:
> > 
> >   https://github.com/jhm15217/worthreading/pull/33
> > 
> > -- Commit Summary --
> > - Added web beacon to email
> > - Connected beacon to server
> > - Log is modified when email open
> > - Tweaking code
> > - Getting web beacon to respond to server
> > - Fixed error
> > - Trying to get db to respond
> > - Some tests for the web beacon
> > - Tweaking again
> > 
> > -- File Changes --
> > 
> > D app/assets/images/rails.png (0)
> > M app/controllers/wr_logs_controller.rb (17)
> > M app/mailers/user_mailer.rb (2)
> > M app/views/user_mailer/send_message.html.haml (6)
> > M app/views/wr_logs/index.html.erb (1)
> > M config/routes.rb (10)
> > A public/images/beacon.gif (0)
> > A public/images/test.jpeg (0)
> > M spec/controllers/wr_logs_controller_spec.rb (14)
> > M spec/mailers/user_mailer_spec.rb (49)
> > 
> > -- Patch Links --
> > 
> >   https://github.com/jhm15217/worthreading/pull/33.patch
> >   https://github.com/jhm15217/worthreading/pull/33.diff
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jhm15217/worthreading/pull/33
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
Yeah just add that.

Do
admin.toggle!(:confirmed)

then after this:
  99.times do |n|
    name  = Faker::Name.name
    email = "example#{n+1}@worth-reading.org"
    password  = "password"
    u = User.create!(name:     name,
                     email:    email,
                     password: password,
                     password_confirmation: password)

add this:
u.toggle!(:confirmed)

On Fri, Jul 27, 2012 at 6:17 PM, James Morris <
reply@reply.github.com

> wrote:
> 
> Maybe have populate mark them all confirmed. I'll try that.
>

**Comment by mvillena3** [comment]
or you can even use the rails console console to do
User.all.each { |u| u.toggle!(:confirmed) }

**Pull request merged**
